### ISSUE TITLE
Show multiple notifications

### ISSUE THREAD

**Issue by miksh7** [naoxink/notifIt#1]
Nice start. It would great if you feature to show multiple notifications at the same time. E.g. how it is done here http://www.jqueryrain.com/?4NmZRZ2C

**Comment by naoxink** [comment]
I improvised this: https://github.com/naoxink/notifIt/commit/ae480fa7194cea6eea83173f82618a50961dbb34

Thank you for your time :)

**Comment by naoxink** [comment]
I'm closing this for the moment. Thank you.
