### ISSUE TITLE
Incorrect Option Name in Demo

### ISSUE THREAD

**Issue by cillosis** [naoxink/notifIt#19]
In the demo at http://naoxink.hol.es/notifIt/, the last one says you can pass `time` to control it. That wasn't working for me, so I referred to the GitHub docs and noticed it is `timeout`. Should probably update that.

![image](https://cloud.githubusercontent.com/assets/1303759/8443621/55bf67fe-1f56-11e5-856f-6740e109d63e.png)

**Comment by naoxink** [comment]
Fixed, Thanks :)
