### ISSUE TITLE
Bottom position out animation has bugs

### ISSUE THREAD

**Issue by Dmurph24** [naoxink/notifIt#20]
When I use the bottom position in the notification, while the notification exits it teleports to the top of the screen instead of falling and fading to the bottom of the screen.

```javascript
notif({
            msg: "<b>Success:</b> Survey was successfully saved",
            bgcolor:"#000000",
            opacity:0.9,
            position:"bottom",
            offset:80,
 })
```

**Comment by naoxink** [comment]
Fixed: https://github.com/naoxink/notifIt/commit/e574358859899d9fdb8a1ebcbe9732e663b3fca1
