### ISSUE TITLE
Exception occurred while notif_confirm() was called in the second time.

### ISSUE THREAD

**Issue by joson** [naoxink/notifIt#22]
**Exception :** 
Uncaught TypeError: $bg.hide is not a function
**Trace:**
    _show	@	notifIt.js:386
    notif_confirm	@	notifIt.js:438

**Cause:**
$bg and $confirm will get the DOM Element but not Jquery Object while notif_confirm() is called second time. See notifIt.js:354-355

**Fixed:**
[Line 354]        var $confirm = $('.notifit_confirm')[0] ? $('.notifit_confirm') : null;
[Line 355]       var $bg = $('.notifit_confirm_bg')[0] ? $('.notifit_confirm_bg') : null;

**Comment by naoxink** [comment]
Changed in https://github.com/naoxink/notifIt/commit/dc89b440c7ec0333c014c49508dcfa212f4eadbd, I don't really have the time now to test, sorry. If you experience some troubles feel free to modify and request a pull :)

Thank you again!
