### ISSUE TITLE
jQuery Conflict

### ISSUE THREAD

**Issue by vnDeveloper** [naoxink/notifIt#23]
Jou!
If use plugin with Prototype Library (Magento):
notifIt/notifIt/js/notifIt.js:328 > Uncaught TypeError: Cannot read property 'animate' of null

**Solution**:
add to **function notif_dismiss()**:
`$ = jQuery;`
like this solved into other plugin functions, but not notif_dismiss()

**Comment by naoxink** [comment]
Thank you, fixed :+1:  https://github.com/naoxink/notifIt/commit/8aed677090384ad7d60ed06198d1e5cbe2297d7f
