### ISSUE TITLE
Modal implementation

### ISSUE THREAD

**Issue by CloudIA** [naoxink/notifIt#8]
Hi, I change your script adding the modal behaviour.

this is my code:

in css:

#ui_overlay_notifIt{
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: #000;
    opacity: 0.5;
    filter: alpha(opacity=50);
    z-index:2;
}

in javascript:
    var overlay = '<div id="ui_overlay_notifIt"></div>'; //NEW
    var defaults = {
        type: "info",
        width: 400,
        height: 60,
        position: "right",
        autohide: 1,
        msg: "This is my default message",
        opacity: 1,
        multiline: 0,
        fade: 0,
        bgcolor: "",
        color: "",
        timeout: 5000,
        modal:false //NEW
    };

    clearInterval(to);
    if(defaults.modal) $("body").append(overlay); //NEW
    $("body").append(div);

function notifit_dismiss(to, config) {
    clearInterval(to);
    if (!config.fade) {
        switch(config.position){
            case "center":
                $("#ui_notifIt").animate({
                    top: parseInt(config.height - (config.height / 2))
                }, 100, function() {
                    $("#ui_notifIt").animate({
                        top: parseInt(0 - (config.height * 2))
                    }, 100, function() {
                        $("#ui_notifIt").remove();
                        if(config.modal)$("#ui_overlay_notifIt").remove(); //NEW
                    });
                });
            break;
            case "right":
                $("#ui_notifIt").animate({
                    right: parseFloat(config.width - (config.width * 0.9))
                }, 100, function() {
                    $("#ui_notifIt").animate({
                        right: parseInt(0 - (config.width * 2))
                    }, 100, function() {
                        $("#ui_notifIt").remove();
                        if(config.modal)$("#ui_overlay_notifIt").remove(); //NEW
                    });
                });
            break;
            case "left":
                $("#ui_notifIt").animate({
                    left: parseFloat(config.width - (config.width * 0.9))
                }, 100, function() {
                    $("#ui_notifIt").animate({
                        left: parseInt(0 - (config.width * 2))
                    }, 100, function() {
                        $("#ui_notifIt").remove();
                        if(config.modal)$("#ui_overlay_notifIt").remove(); //NEW
                    });
                });
            break;
        }
    } else {
        $("#ui_notifIt").fadeOut("slow", function() {
            $("#ui_notifIt").remove();
            if(config.modal)$("#ui_overlay_notifIt").remove(); //NEW
        });
    }
}

thanks for your work 
Marco

**Comment by naoxink** [comment]
I'm closing this issue for no response.

P.S.: I have no plans about implement this in the near future.
